dist: bionic
language: ruby
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
before_install:
  - gem install bundler
script: "bundle exec rake appraisal:test"
sudo: true
services:
  - redis-server
  - memcached
  - rabbitmq
  - mysql
addons:
  apt:
    sources:
      - sourceline: "deb https://packages.erlang-solutions.com/ubuntu bionic contrib"
        key_url: "https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc"
      - sourceline: "deb https://dl.bintray.com/rabbitmq/debian bionic main"
        key_url: "https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc"
    packages:
      - rabbitmq-server
